# Site settings
title: Retrofuturismo con alecu
email: alecu@protocultura.net
description: > # this means to ignore newlines until "baseurl:"
  Ubuntu, Python and electromechanical games.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alecu.protocultura.net" # the base hostname & protocol for your site
twitter_username: alecura
github_username:  alecu
launchpad_username: alecu
logo: alecu192.jpg

# Build settings
markdown: kramdown
